server:
  port: 8084

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product_service_route
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: catalog_service_route
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: inventory_service_route
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/