server:
  port: 8083

spring:
  application:
    name: product-service

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    catalogService:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slidingWindowSize: 5
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 2
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

    inventoryService:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slidingWindowSize: 5
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 2
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true